import React from "react";
import { enhanceCustomOverlay } from "../utils/enhanceCustomOverlays";

/**
 * Example of a simple AI-generated overlay without hover controls
 * This represents what might have been generated by AI
 */
const SimpleAIGeneratedOverlay = ({ title, color, contentElement }) => {
  return (
    <div style={{ 
      padding: "15px", 
      backgroundColor: color || "#f9f9f9",
      borderRadius: "6px",
      boxShadow: "0 2px 8px rgba(0,0,0,0.1)"
    }}>
      <h3 style={{ margin: "0 0 10px 0", color: "#333" }}>{title}</h3>
      <div style={{ color: "#555" }}>{contentElement}</div>
    </div>
  );
};

/**
 * Enhanced version of the AI-generated overlay with hover controls
 * This adds the hover buttons, dragging functionality, etc.
 */
const EnhancedAIOverlay = enhanceCustomOverlay(SimpleAIGeneratedOverlay);

/**
 * Usage example component that demonstrates how to use the enhanced overlay
 */
const AIGeneratedOverlayExample = () => {
  // Handler for when the user clicks delete
  const handleDelete = () => {
    console.log("Delete was clicked");
    alert("Delete button clicked!");
  };
  
  // Handler for when the user toggles pinning
  const handlePin = (isPinned: boolean) => {
    console.log("Pin state changed:", isPinned);
    alert(`Overlay is now ${isPinned ? "pinned" : "unpinned"}`);
  };
  
  return (
    <div style={{ padding: "20px" }}>
      <h2>Enhanced AI-Generated Overlay Example</h2>
      <p>
        This example shows how to enhance an existing AI-generated overlay
        with the same hover buttons and positioning as DynamicOverlay
      </p>
      
      <div style={{ height: "400px", position: "relative", border: "1px dashed #ccc", marginTop: "20px" }}>
        <p style={{ textAlign: "center", marginTop: "10px" }}>
          Hover over the overlay below to see the buttons
        </p>
        
        {/* This is the enhanced AI-generated overlay */}
        <EnhancedAIOverlay 
          // Props for the enhancer
          id={1}
          style={{ 
            top: 100, 
            left: 100,
            width: 300,
            backgroundColor: "#ffffff"
          }}
          url={window.location.href}
          onDelete={handleDelete}
          onPin={handlePin}
          content="This is the content that will be copied when using the copy button"
          
          // Props for the original AI component
          title="Enhanced AI Overlay"
          color="#ffffff"
          contentElement={
            <div>
              <p>This overlay now has the same hover controls as DynamicOverlay!</p>
              <p>Try hovering over it to see the buttons appear.</p>
              <p>You can:</p>
              <ul>
                <li>Drag it around</li>
                <li>Pin/unpin it</li>
                <li>Delete it</li>
                <li>Copy its content</li>
                <li>Share it with others</li>
              </ul>
            </div>
          }
        />
      </div>
    </div>
  );
};

export default AIGeneratedOverlayExample; 